# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-29 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30)),
                ('issueType', models.CharField(max_length=30)),
                ('issuePriority', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('affectsVersion', models.CharField(max_length=30)),
                ('foundInBuild', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('resolution', models.CharField(default='Unresolved', max_length=30)),
                ('status', models.CharField(default='Open', max_length=30)),
                ('votes', models.IntegerField(default=0)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('issueId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bugDB.Issue')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
