# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=30)),
                ('issueType', models.CharField(max_length=30)),
                ('issuePriority', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('affectsVersion', models.CharField(max_length=30)),
                ('foundInBuild', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=30)),
                ('reporter', models.CharField(max_length=30)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now_add=True)),
                ('closedDate', models.DateTimeField()),
            ],
        ),
    ]
