# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='resolution',
            field=models.CharField(default='Unresolved', max_length=30),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(default='Open', max_length=30),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
