# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='projectName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bugDB.IssueProject'),
        ),
    ]
