# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-22 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='closedDate',
        ),
    ]
