# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugDB', '0002_auto_20190506_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='projectName',
            field=models.CharField(max_length=150),
        ),
    ]
