# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-06 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugDB', '0003_auto_20190506_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='projectName',
            new_name='issueProjectName',
        ),
    ]
